### ISSUE TITLE
sum() better than "running_total"

### ISSUE THREAD

**Issue by eatpro** [kplaisted5/Murder-Mystery#1]
In the for loop where you calculate the average sentence length, you keep track of the length of all sentences with a running total variable which is ran each time the loop is ran. This works fine but as a best practice, you should always use language features when possible as they are built to be robust and efficient. In this case, adding all the sentence lengths to the array is a good approach but it would be more efficient to use the sum() function after the loop has.

```average = sum(sentence_lengths) / len(sentence_lengths)```

**Comment by kplaisted5** [comment]
Thank you!
