### ISSUE TITLE
Use string.format when possible

### ISSUE THREAD

**Issue by eatpro** [kplaisted5/Murder-Mystery#2]
If possible, it is easier to read, understand and avoid bugs if you use string templates (string.format())

Using the "+" operator works fine but can cause unintended results when variables are not of expected types. See below for an example.

```diff
-ngram_list.append(text_list[x]+" "+text_list[x+1])
```
```diff
+ngrams.append('{} {}'.format(ltext_list[x], text_list[x+1]))
```

**Comment by kplaisted5** [comment]
Ahhhh smart! Thank you!
