### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by eatpro** [kplaisted5/Murder-Mystery#3]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ All code is valid and well formatted
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4
* _Comment(s):_ All project requirements met, looks great
 
### Criteria 3: Software Architecture
* _Score Level:_ 4
* _Comment(s):_ All classes and functions are well defined and free of most inefficiencies
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ A lot of Python features are used but there are a few instances where language features should have been used but weren't. See other issues for details. 

### Criteria 5: Produces Accurate Output
* _Score Level:_ 4
* _Comment(s):_ All output is accurate and you chose correctly whodunnit!
 
### Overall Score: 19/20
Overall this project is great! Code looks good, is efficient and implemented correctly. Just remember to always think about powerful language feature which can be used while developing. Keep it up and happy coding!

**Comment by kplaisted5** [comment]
Thanks for the review!
